# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
